### ISSUE TITLE
Suggestion: Have a Button to switch the sides of the Players

### ISSUE THREAD

**Issue by PaulDepping** [Readek/Melee-Stream-Tool#1]
When running an event with a Camera, often times the players sit in a different order than expected, having a single button switch the sides of the players would be very helpful. As an example, going from this: 
![image](https://user-images.githubusercontent.com/56696636/93754253-bc261280-fc01-11ea-888a-2179a215cdd4.png)
to this: 
![image](https://user-images.githubusercontent.com/56696636/93754317-d19b3c80-fc01-11ea-8a3d-a1002b6dec64.png)
currently requires you to retype everything and reset characters and score, and as this is something that I as a TO think is quite frequent having a single button swap them would be great.

**Comment by Readek** [comment]
Yeah this is a bad design choice im not happy about. Theres actually a swap button, it's on the mid bar separating both characters, but theres nothing there to indicate it exists aside from the icon when hovering.

**Comment by PaulDepping** [comment]
Oh wow, didnt notice, im gonna close this then since its already in the current build, my bad for not searching hard enough.
